# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-18 23:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myprofile',
            name='nick_name',
            field=models.CharField(default='nickname', max_length=30),
            preserve_default=False,
        ),
    ]
