# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-15 09:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_address',
            name='city',
        ),
        migrations.RemoveField(
            model_name='user_address',
            name='country',
        ),
        migrations.RemoveField(
            model_name='user_address',
            name='district',
        ),
        migrations.RemoveField(
            model_name='user_address',
            name='province',
        ),
        migrations.AddField(
            model_name='user_address',
            name='user_city',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_city', to='address.District', verbose_name='市'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user_address',
            name='user_country',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='address.Country', verbose_name='国家'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user_address',
            name='user_district',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_district', to='address.District', verbose_name='区'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user_address',
            name='user_province',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_province', to='address.District', verbose_name='省'),
            preserve_default=False,
        ),
    ]
