# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-24 18:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0002_auto_20170115_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_address',
            name='detail_address',
            field=models.CharField(max_length=200, verbose_name='详细地址'),
        ),
        migrations.AlterField(
            model_name='user_address',
            name='postcode',
            field=models.PositiveIntegerField(verbose_name='邮编'),
        ),
        migrations.AlterField(
            model_name='user_address',
            name='receiver_name',
            field=models.CharField(max_length=50, verbose_name='收信人'),
        ),
    ]
