# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-30 19:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0004_user_address_is_deleted'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User_Address',
            new_name='UserAddress',
        ),
    ]
