# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-14 12:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import posts.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('address', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('post_title', models.CharField(max_length=200)),
                ('post_description', models.TextField()),
                ('post_quantity', models.PositiveIntegerField()),
                ('card_left', models.IntegerField(default=0)),
                ('post_picture', models.ImageField(blank=True, null=True, upload_to=posts.models.user_directory_path)),
                ('post_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='city', to='address.District')),
                ('post_country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='address.Country')),
                ('post_district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='district', to='address.District')),
                ('post_province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='province', to='address.District')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.MyProfile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
