# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-05 21:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('address', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('post_title', models.CharField(max_length=200)),
                ('post_description', models.TextField()),
                ('post_quantity', models.IntegerField()),
                ('post_picture', models.CharField(max_length=200)),
                ('post_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='City', to='address.District')),
                ('post_country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Country', to='address.Country')),
                ('post_province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Province', to='address.District')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.MyProfile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
