# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-26 22:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0003_auto_20170125_0237'),
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardclaim',
            name='claimer_address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='address.User_Address'),
        ),
    ]
