# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-15 09:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import posts.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20170115_0452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='card_left',
            field=models.IntegerField(default=0, verbose_name='待领取'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_city',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='city', to='address.District', verbose_name='寄片的城市'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='post_country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='address.Country', verbose_name='寄片的国家与地区'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_description',
            field=models.TextField(verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_district',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='district', to='address.District', verbose_name='寄片的区县'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='post_picture',
            field=models.ImageField(blank=True, null=True, upload_to=posts.models.user_directory_path, verbose_name='上传一张图片'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_province',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='province', to='address.District', verbose_name='寄片的省'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='post_quantity',
            field=models.PositiveIntegerField(verbose_name='发片数量'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_title',
            field=models.CharField(max_length=200, verbose_name='发片令标题'),
        ),
    ]
