# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-29 03:06
from __future__ import unicode_literals

from django.db import migrations, models
import posts.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_cardclaim_claimer_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_picture',
            field=models.ImageField(upload_to=posts.models.post_directory_path, verbose_name='上传一张图片'),
        ),
    ]
