# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-12 10:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20170112_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_city',
            field=models.IntegerField(choices=[[0, '------']], max_length=6),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_district',
            field=models.IntegerField(choices=[[0, '------']], max_length=6),
        ),
    ]
