# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-12 11:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20170112_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_city',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_district',
            field=models.IntegerField(),
        ),
    ]
