# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-13 09:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_auto_20170113_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_province',
            field=models.IntegerField(),
        ),
    ]
