# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-13 09:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_auto_20170113_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_picture',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
