# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-13 21:24
from __future__ import unicode_literals

from django.db import migrations, models
import posts.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_auto_20170113_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_picture',
            field=models.FileField(blank=True, null=True, upload_to=posts.models.user_directory_path),
        ),
    ]
