# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-14 02:34
from __future__ import unicode_literals

from django.db import migrations, models
import posts.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_auto_20170114_0524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_picture',
            field=models.ImageField(blank=True, null=True, upload_to=posts.models.user_directory_path),
        ),
    ]
