# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-14 04:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0014_auto_20170114_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='city', to='address.District'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='address.Country'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='district', to='address.District'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='province', to='address.District'),
        ),
    ]
